# Generated by Django 5.1.15 on 2026-06-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'システム管理者'), ('leader', 'リーダー'), ('crew', 'クルー')], default='crew', max_length=16, verbose_name='ロール'),
        ),
    ]
