# Generated by Django 5.1.15 on 2026-06-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remap_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fixed_shift_editable_by_crew',
            field=models.BooleanField(default=False, help_text='オンにすると、このクルー本人が自分の固定シフトを編集できます。', verbose_name='本人による固定シフト編集を許可'),
        ),
    ]
