# Generated by Django 5.1.15 on 2026-06-06 15:57

import django.db.models.deletion
import shifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='タイトル')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('deadline', models.DateTimeField(verbose_name='締切日時')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '締切後')], default='open', max_length=16, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_periods', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '対象期間',
                'verbose_name_plural': '対象期間',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ConfirmedShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=shifts.models.confirmed_shift_upload_path, verbose_name='ファイル')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_shifts', to=settings.AUTH_USER_MODEL, verbose_name='アップロード者')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmed_shifts', to='shifts.shiftperiod', verbose_name='対象期間')),
            ],
            options={
                'verbose_name': '確定シフト',
                'verbose_name_plural': '確定シフト',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='備考・連絡事項')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='最終提出日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='初回提出日時')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='shifts.shiftperiod', verbose_name='対象期間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to=settings.AUTH_USER_MODEL, verbose_name='提出者')),
            ],
            options={
                'verbose_name': 'シフト希望',
                'verbose_name_plural': 'シフト希望',
            },
        ),
        migrations.CreateModel(
            name='ShiftRequestDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='対象日')),
                ('is_available', models.BooleanField(default=True, verbose_name='出勤可')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='開始時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='終了時刻')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='shifts.shiftrequest', verbose_name='提出')),
            ],
            options={
                'verbose_name': '各日の希望',
                'verbose_name_plural': '各日の希望',
                'ordering': ['work_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.PositiveIntegerField(verbose_name='バージョン')),
                ('snapshot', models.JSONField(verbose_name='内容スナップショット')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='shifts.shiftrequest', verbose_name='提出')),
            ],
            options={
                'verbose_name': '変更履歴',
                'verbose_name_plural': '変更履歴',
                'ordering': ['-version_no'],
            },
        ),
        migrations.AddConstraint(
            model_name='shiftrequest',
            constraint=models.UniqueConstraint(fields=('period', 'user'), name='unique_request_per_user_period'),
        ),
        migrations.AddConstraint(
            model_name='shiftrequestday',
            constraint=models.UniqueConstraint(fields=('request', 'work_date'), name='unique_day_per_request'),
        ),
        migrations.AddConstraint(
            model_name='shiftrequesthistory',
            constraint=models.UniqueConstraint(fields=('request', 'version_no'), name='unique_version_per_request'),
        ),
    ]
