# Generated by Django 5.1.15 on 2026-06-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0003_normalize_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftperiod',
            name='edit_deadline',
            field=models.DateTimeField(blank=True, help_text='「締切後も編集可」のとき、ここまで編集可能（自動締切）。空なら手動で締め切るまで編集可。', null=True, verbose_name='編集最終期限'),
        ),
        migrations.AddField(
            model_name='shiftperiod',
            name='post_deadline_policy',
            field=models.CharField(choices=[('lock_all', '締切後は提出・編集とも不可'), ('late_submit', '未提出者は提出可・編集は不可'), ('editable', '締切後も編集可（編集最終期限まで）')], default='late_submit', max_length=16, verbose_name='締切後の扱い'),
        ),
    ]
