# Generated by Django 5.1.15 on 2026-06-06 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0004_shiftperiod_edit_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftperiod',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='オフにするとスタッフのホームに表示されません（リーダーは管理画面で操作できます）。', verbose_name='スタッフに表示'),
        ),
    ]
