# Generated by Django 5.1.15 on 2026-06-09 20:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0006_weeklyfixedshift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '保留'), ('approved', '承認'), ('rejected', '却下')], default='pending', max_length=16, verbose_name='状態')),
                ('payload', models.JSONField(help_text='[{weekday, is_available, start_time, end_time}, ...] の7曜日分', verbose_name='提案内容')),
                ('crew_comment', models.TextField(blank=True, verbose_name='申請コメント')),
                ('review_comment', models.TextField(blank=True, verbose_name='処理コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='処理日時')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fixed_shift_requests', to=settings.AUTH_USER_MODEL, verbose_name='処理者')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_shift_requests', to=settings.AUTH_USER_MODEL, verbose_name='申請者')),
            ],
            options={
                'verbose_name': '固定シフト変更申請',
                'verbose_name_plural': '固定シフト変更申請',
                'ordering': ['-created_at'],
            },
        ),
    ]
