# Generated by Django 5.1.15 on 2026-06-09 22:10

import django.db.models.deletion
import shifts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0007_fixedshiftchangerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_on_confirmed', models.BooleanField(default=True, verbose_name='確定シフト公開時に自動投稿')),
                ('auto_on_period', models.BooleanField(default=True, verbose_name='対象期間の追加時に自動投稿')),
            ],
            options={
                'verbose_name': 'お知らせ自動投稿設定',
                'verbose_name_plural': 'お知らせ自動投稿設定',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('body', models.TextField(blank=True, verbose_name='本文')),
                ('category', models.CharField(choices=[('manual', 'お知らせ'), ('confirmed', '確定シフト'), ('period', '期間追加')], default='manual', max_length=16, verbose_name='種別')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('related_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='shifts.shiftperiod', verbose_name='関連する対象期間')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=shifts.models.announcement_upload_path, verbose_name='ファイル')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='元ファイル名')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shifts.announcement', verbose_name='お知らせ')),
            ],
        ),
        migrations.CreateModel(
            name='AnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='既読日時')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='shifts.announcement', verbose_name='お知らせ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL, verbose_name='閲覧者')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('announcement', 'user'), name='unique_announcement_read')],
            },
        ),
    ]
