# Generated by Django 5.1.15 on 2026-06-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0008_announcementsettings_announcement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementsettings',
            name='auto_on_confirmed',
        ),
    ]
