# Generated by Django 5.1.15 on 2026-06-10 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0009_remove_announcementsettings_auto_on_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at'], 'verbose_name': 'アナウンス', 'verbose_name_plural': 'アナウンス'},
        ),
        migrations.AlterModelOptions(
            name='announcementsettings',
            options={'verbose_name': 'アナウンス自動投稿設定', 'verbose_name_plural': 'アナウンス自動投稿設定'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='level',
            field=models.CharField(choices=[('info', '情報'), ('warning', '注意'), ('danger', '警告'), ('success', '完了')], default='info', max_length=16, verbose_name='表示レベル'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='category',
            field=models.CharField(choices=[('manual', 'アナウンス'), ('confirmed', '確定シフト'), ('period', '期間追加')], default='manual', max_length=16, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='shifts.announcement', verbose_name='アナウンス'),
        ),
        migrations.AlterField(
            model_name='announcementread',
            name='announcement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='shifts.announcement', verbose_name='アナウンス'),
        ),
    ]
