# Generated by Django 5.1.15 on 2026-06-11 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_label', models.CharField(blank=True, max_length=150, verbose_name='操作者名')),
                ('action', models.CharField(choices=[('login', 'ログイン'), ('logout', 'ログアウト'), ('account_create', 'アカウント作成'), ('account_edit', 'アカウント編集'), ('account_delete', 'アカウント削除'), ('account_reset_pw', 'パスワード再発行'), ('account_toggle_active', '有効/無効化'), ('account_toggle_fixed', '固定シフト編集許可の変更'), ('period_create', '期間作成'), ('period_edit', '期間編集'), ('period_close', '期間の締切/再開'), ('period_visibility', '期間の表示/非表示'), ('period_delete', '期間削除'), ('shift_submit', 'シフト希望の提出/編集'), ('confirmed_upload', '確定シフトのアップロード'), ('confirmed_delete', '確定シフトの削除'), ('announce_create', 'アナウンス投稿'), ('announce_edit', 'アナウンス編集'), ('announce_delete', 'アナウンス削除'), ('announce_settings', 'アナウンス自動投稿設定'), ('fixed_edit', '固定シフトの編集'), ('fixed_request', '固定シフト変更申請'), ('fixed_request_cancel', '固定シフト申請の取消'), ('fixed_request_review', '固定シフト申請の承認/却下')], db_index=True, max_length=32, verbose_name='操作の種類')),
                ('summary', models.CharField(max_length=255, verbose_name='内容')),
                ('target', models.CharField(blank=True, max_length=255, verbose_name='対象')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='日時')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作者')),
            ],
            options={
                'verbose_name': '監査ログ',
                'verbose_name_plural': '監査ログ',
                'ordering': ['-created_at'],
            },
        ),
    ]
